### ISSUE TITLE
Is this thing intendent to work?

### ISSUE THREAD

**Issue by Gordon01** [TerraBAS/mopidy-lcd#1]
I want to output song name to 16x2 LCD from Mopidy, found your progect but have absolutely no idea how no configure it or to connect to LCD. 
What LCD should I use? Controller type?

**Comment by TerraBAS** [comment]
updated Readme.md

I programmed it for an Adafruit 16x2 Multicolor LCD with the Hitachi HD44780 LCD controller.

Just install it following the tutorial on adafruit and then run main.py under the "mopidy-lcd" directory.

**Comment by Gordon01** [comment]
So this is no more mopidy extension? After installation it installs to /usr/local/lib/python2.7/dist-packages/mopidy-lcd/ but I dont see any related lines in mopidy log.

**Comment by TerraBAS** [comment]
No, it's an external script that only accesses the mopidy API. Also I suggest to download the "mopidy-lcd" directory manual on your system and setting an cron to automatically start it with mopidy. Automatic installation is currently not working...

**Comment by Gordon01** [comment]
I have ordinary hd44780 display connected to rpi directly, Adafruit_CharLCD library works fine, but it lacks classes like createChar, etc. 
Maybe you have stripped down version, that just outputs song name? :)

**Comment by Gordon01** [comment]
Ok, got it working with my display, but for some reason not connecting to mpd

**Comment by TerraBAS** [comment]
When mpd started, it needs a while to respond to requests (max 5min). Just let the display stay on "Could not connect" and if mpd is available it will automatically retry to connect.
